openapi: 3.0.0
info:
  title: User Management
  version: 1.0.0
servers:
  - url: http://localhost:5000
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/v1/auth/signin:
    patch:
      tags:
        - default
      summary: Signin
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: user@yopmail.com
                password: Vikas@123
      security:
        - bearerAuth: []
      parameters:
        - name: Accept-Language
          in: header
          schema:
            type: string
          example: en
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            kjghfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '500':
          description: Internal Server Error.
          content:
            application/json: {}
  /api/v1/auth/forgot-password:
    post:
      tags:
        - default
      summary: send-otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                phone_no: '9875848149'
                email: 'abc@gmail.com'
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            kjghfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
        - name: Accept-Language
          in: header
          schema:
            type: string
          example: hn
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '500':
          description: Internal Server Error.
          content:
            application/json: {}
  /api/v1/auth/verify-otp:
    post:
      tags:
        - default
      summary: verify-otp
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                otp: '998'
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            kjghfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
        - name: token
          in: header
          schema:
            type: string
          example: >-
            uiighfhdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '500':
          description: Internal Server Error.
          content:
            application/json: {}
  /api/v1/auth/logout:
    post:
      tags:
        - default
      summary: Logout
      requestBody:
        content: {}
      security:
        - bearerAuth: []
      parameters:
        - name: x-api-key
          in: header
          schema:
            type: string
          example: >-
            jhhjghdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer jhhjghdfsshgndcljdjsflsdfljuy575itjkshkjoujoiuhjdjkjkjshskkjkjhsjkhjkhjkshkj
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
        '500':
          description: Internal Server Error.
          content:
            application/json: {}



            